# Generated by Django 3.2.22 on 2023-10-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя менеджера')),
                ('tg_id', models.PositiveIntegerField(unique=True, verbose_name='Telegram_id')),
                ('time', models.PositiveIntegerField(choices=[(1, 'Утро'), (2, 'Вечер')], db_index=True, default=3, verbose_name='Доступное время')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя ученика')),
                ('tg_id', models.PositiveIntegerField(unique=True, verbose_name='Telegram_id')),
                ('skills', models.PositiveIntegerField(choices=[(1, 'Beginner'), (2, 'Beginner+'), (3, 'Junior')], db_index=True, default=1, verbose_name='Навыки')),
                ('time', models.PositiveIntegerField(choices=[(1, '14.00-18.00'), (2, '18.00-22.00'), (3, 'Any Time')], db_index=True, default=3, verbose_name='Доступное время')),
                ('place_residence', models.BooleanField(default=False, verbose_name='Дальний восток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Участвует в проекте')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('time', models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30')], default='12:00', max_length=5, verbose_name='время проведения')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='bot.manager', verbose_name='Менеджер')),
                ('students', models.ManyToManyField(related_name='projects', to='bot.Student', verbose_name='Ученики')),
            ],
        ),
    ]
