# Generated by Django 4.2.2 on 2023-10-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Имя менеджера')),
                ('tg_id', models.PositiveIntegerField(unique=True, verbose_name='Telegram_id')),
            ],
        ),
    ]
